services:
  yggdrasil:
    image: yggdrasil
    build:
      context: .
      dockerfile: Yggdrasil/Dockerfile
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"